### ISSUE TITLE
dist/ is in global gitignore file

### ISSUE THREAD

**Issue by rhjones** [ga-wdi-boston/ember-deployment-guide#5]
Heads up to other developers: you'll either need to comment out `/dist` from your **global** gitignore file (`~/.gitignore`) in addition to the `.gitignore` file in your `gh-pages` branch to track the `dist` directory here or forcibly add files within that directory to your repo (`git add -f`).

(This was an issue with [deploying Rails apps to Heroku](https://github.com/ga-wdi-boston/full-stack-project/issues/395) as well. It looks like this has [already been addressed](https://github.com/ga-wdi-boston/orientation/issues/166) in the installfest.)

**Comment by jrhorn424** [comment]
I believe this has been addressed as of https://github.com/ga-wdi-boston/ember-template/commit/24d60a9d23fa979e6f964e10bba910fa4a42d39f

**Comment by jrhorn424** [comment]
Thanks again @rhjones
